[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'
[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 88
multi_line_output = 3
known_first_party = ["config"]
[flake8]
max-line-length = 88
ignore = F401, F403, F405, E501, W503, F541, F821, F841
per-file-ignores =
    config/settings/*:F405 F403 F401
[tool.djlint]
profile = "django"
ignore = "H020,H021,H031"
line_length = 88
